version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - CI=true
    command: npm run test:ci

  test:watch:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - WATCHPACK_POLLING=true
    command: npm run test:watch
    tty: true

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - CYPRESS_baseUrl=http://app:3000
    depends_on:
      - app
    command: npm run cypress:run

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm start
