name: Backend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'safetypin-backend/**'
      - '.github/workflows/backend-testing.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'safetypin-backend/**'
      - '.github/workflows/backend-testing.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: safetypin_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'safetypin-backend/package-lock.json'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./safetypin-backend
      
      - name: Lint
        run: npm run lint -- --max-warnings=0
        working-directory: ./safetypin-backend
      
      - name: Run tests
        run: npm test -- --coverage
        working-directory: ./safetypin-backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/safetypin_test
          NODE_ENV: test
          JWT_SECRET: test-secret
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./safetypin-backend/coverage
          flags: backend
